package project_euler

import scala.annotation.tailrec

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 * */

object Problem_2 extends App{
	
  val limit = 4000000L                            //> limit  : Long = 4000000
  
 def fibLoop():Long =
  {
	  var x = 1L
	  var y = 2L
	  var sum = 0L
	  var swap = 0L
  
	  while(x < limit)
	  {
	    if(x % 2 ==0) sum +=x
	    swap = x
	    x = y
	    y = swap + x
	  }
	  sum
  }                                               //> fibLoop: ()Long
 def fib:Int = {
   lazy val fs: Stream[Int] = 0 #:: 1 #:: fs.zip(fs.tail).map(p => p._1 + p._2)
   fs.view.takeWhile(_ <= limit).filter(_ % 2 == 0).sum
 }                                                //> fib: => Int
 
   val t1 = System.nanoTime()                     //> t1  : Long = 88451310977178
   val res = fib                                  //> res  : Int = 4613732
   val t2 = (System.nanoTime() - t1 )/1000        //> t2  : Long = 93421
   println(s"The result is: $res time taken $t2 ms ")
                                                  //> The result is: 4613732 time taken 93421 ms 

}